### ISSUE TITLE
CMake Fix the correct output folder

### ISSUE THREAD

**Issue by Meraz** [Poelsa/need-hug#18]
MS VS puts things in in ${CMAKE_RUNTIME_OUTPUT_DIRECTORY} followed by a sub-folder called either release or debug. Make seeems to do it using another scheme. Remember this when fixing it. 

I tried to fix it in 4e41c7be7e2f3da3590041bd0f1fc64c9ba3cfdc and I got it to work (or so I thought)... it should not work at all with the current solution. And note to my future self: PUSH THINGS ON A BRANCH even if it is part of the build-system. Or rather especially if the changes modifies the build-system.

**Comment by Poelsa** [comment]
On Linux another "build" directory is created inside the first "build" directory.
