### ISSUE TITLE
Find which libraries are needed for building SFML on Fedora

### ISSUE THREAD

**Issue by Poelsa** [Poelsa/need-hug#22]
Currently:
sfml-devel.x86_64
mesa-libGL-devel.x86_64

**Comment by Poelsa** [comment]
Also:
systemd-devel.x86_64
libjpeg-turbo-devel.x86_64
freetype-devel.x86_64

**Comment by Meraz** [comment]
Does not work for Mint, I need us to verify that it would work for Fedora as well.

**Comment by Meraz** [comment]
We (I) missunderstood the problem. It works with the information above.
